server:
  image: liqk1989/ngrok
  ports:
    - "8080:8080"
    - "8081:8081"
    - "4443:4443"
  volumes:
    - ~/docker-ngrok/out:/myfiles
  environment:
    - DOMAIN=svod.app
    - TUNNEL_ADDR=:4443
    - HTTP_ADDR=:8080
    - HTTPS_ADD=:8081
  command: /bin/sh /server.sh
  container_name: ngrok-server
